CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6),
    deleted_at TIMESTAMP(6),
    PRIMARY KEY (id)
);


CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    price DECIMAL(38, 2) NOT NULL,
    category_id BIGINT NOT NULL,
    image VARCHAR(255),
    rating VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6),
    deleted_at TIMESTAMP(6),
    PRIMARY KEY (id),

    CONSTRAINT fk_product_category
        FOREIGN KEY (category_id)
        REFERENCES categories (id)
);


CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    status SMALLINT,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6),
    deleted_at TIMESTAMP(6),
    PRIMARY KEY (id)
);


CREATE TABLE order_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6),
    deleted_at TIMESTAMP(6),
    PRIMARY KEY (id),

    CONSTRAINT fk_order_product
        FOREIGN KEY (order_id)
        REFERENCES orders (id),

    CONSTRAINT fk_product_order
        FOREIGN KEY (product_id)
        REFERENCES products (id)
);