CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(255),
    description TEXT,
    rating DECIMAL(3,1),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6),
    deleted_at TIMESTAMP(6),
    product_id  BIGINT NOT NULL,
    order_id  BIGINT NOT NULL,
    PRIMARY KEY (id),

    CONSTRAINT fk_review_product
        FOREIGN KEY (product_id)
        REFERENCES products (id),

    CONSTRAINT fk_review_order
        FOREIGN KEY (order_id)
        REFERENCES orders (id)
);